package:
  name: libxml
  version: 2.14.6
  tag:
    - library
    - static_library
source:
  sha256: 7ce458a0affeb83f0b55f1f4f9e0e55735dbfc1a9de124ee86fb4a66b597203a
  url: https://download.gnome.org/sources/libxml2/2.14/libxml2-2.14.6.tar.xz

requirements:
  host:
    - libzlib
    - libiconv

build:
  type: static_library
  script: |
    emconfigure ./configure \
        CFLAGS="-fPIC" \
        --disable-dependency-tracking \
        --disable-shared \
        --without-python \
        --with-iconv="${WASM_LIBRARY_DIR}" \
        --with-zlib="${WASM_LIBRARY_DIR}" \
        --with-lzma="no" \
        --prefix=${WASM_LIBRARY_DIR}
    emmake make -j ${PYODIDE_JOBS:-3}
    emmake make install
about:
  home: https://gitlab.gnome.org/GNOME/libxml2
  license: MIT
